// Code generated by goctl. DO NOT EDIT!
// Source: expand.proto

package expander

import "errors"

var errJsonConvert = errors.New("json convert error")

type (
	ExpandReq struct {
		Key string `json:"key,omitempty"`
	}

	ExpandResp struct {
		Url string `json:"url,omitempty"`
	}
)
