// Code generated by goctl. DO NOT EDIT!
// Source: shorten.proto

package shortener

import "errors"

var errJsonConvert = errors.New("json convert error")

type (
	ShortenReq struct {
		Url string `json:"url,omitempty"`
	}

	ShortenResp struct {
		Key string `json:"key,omitempty"`
	}
)
