// DO NOT EDIT, generated by goctl
package types

type ExpandReq struct {
	Key string `form:"key"`
}

type ExpandResp struct {
	Url string `json:"url"`
}

type ShortenReq struct {
	Url string `form:"url"`
}

type ShortenResp struct {
	ShortUrl string `json:"shortUrl"`
}
