// Code generated by goctl. DO NOT EDIT!
// Source: shorten.proto

package server

import (
	"context"

	"shorturl/rpc/shorten/internal/logic"
	"shorturl/rpc/shorten/internal/svc"
	shorten "shorturl/rpc/shorten/pb"
)

type ShortenerServer struct {
	svcCtx *svc.ServiceContext
}

func NewShortenerServer(svcCtx *svc.ServiceContext) *ShortenerServer {
	return &ShortenerServer{
		svcCtx: svcCtx,
	}
}

func (s *ShortenerServer) Shorten(ctx context.Context, in *shorten.ShortenReq) (*shorten.ShortenResp, error) {
	l := logic.NewShortenLogic(ctx, s.svcCtx)
	return l.Shorten(in)
}
