// Code generated by goctl. DO NOT EDIT!
// Source: shorten.proto

package main

import (
	"flag"
	"fmt"
	"log"

	"shorturl/rpc/shorten/internal/config"
	"shorturl/rpc/shorten/internal/server"
	"shorturl/rpc/shorten/internal/svc"
	shorten "shorturl/rpc/shorten/pb"

	"github.com/tal-tech/go-zero/core/conf"
	"github.com/tal-tech/go-zero/rpcx"
	"google.golang.org/grpc"
)

var configFile = flag.String("f", "etc/shorten.yaml", "the config file")

func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)
	ctx := svc.NewServiceContext(c)
	shortenerSrv := server.NewShortenerServer(ctx)

	s, err := rpcx.NewServer(c.RpcServerConf, func(grpcServer *grpc.Server) {
		shorten.RegisterShortenerServer(grpcServer, shortenerSrv)
	})
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("Starting rpc server at %s...\n", c.ListenOn)
	s.Start()
}
